apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-role
  namespace: default
  labels:
    app: role-for-init
rules:
  # Error from server (Forbidden): jobs.batch "test-job-check-status" is forbidden:
  # User "system:serviceaccount:default:default" cannot get
  # resource "jobs" in API group "batch" in the namespace "default"
  # @see https://kubernetes.io/docs/reference/access-authn-authz/rbac/
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]