apiVersion: v1
kind: Namespace
metadata:
  name: learn-sec
---
apiVersion: v1
data:
  password: UyFCXCpkJHpEc2I9
  username: VG9tYXNzbyANCg==
kind: Secret
metadata:
  name: db-cred
  namespace: learn-sec