apiVersion: batch/v1
kind: Job
metadata:
  name: get-env
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: get-env
          image: busybox
          command: ["sh", "-c"]
          args:
            - |
              printenv
              echo "------------------------------\n";
              env