apiVersion: batch/v1
kind: CronJob
metadata:
  name: testcronjobdemo
spec:
  # see detail, https://pkg.go.dev/github.com/robfig/cron/v3#hdr-CRON_Expression_Format
  #          ┌───────────── minute (0 - 59)
  #          │ ┌───────────── hour (0 - 23)
  #          │ │ ┌───────────── day of the month (1 - 31)
  #          │ │ │ ┌───────────── month (1 - 12)
  #          │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
  #          │ │ │ │ │                                   7 is also Sunday on some systems)
  #          │ │ │ │ │                                   OR sun, mon, tue, wed, thu, fri, sat
  #          │ │ │ │ │
  #          * * * * *  
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: testcronjob
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure