# https://medium.com/google-cloud/understanding-kubernetes-networking-services-f0cb48e4cc82
kind: Deployment
apiVersion: apps/v1
metadata:
  name: service-test-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service_test_pod
  template:
    metadata:
      labels:
        app: service_test_pod
    spec:
      containers:
      - name: simple-http
        image: python:2.7
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["-c", "echo \"<p>Hello from $(hostname)</p>\" > index.html; python -m SimpleHTTPServer 8080"]
        ports:
        - name: http
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: service-test-server
spec:
  selector:
    app: service_test_pod
  ports:
  - port: 80
    targetPort: http